version: '3'

services:

  server:
    build: ./server
    volumes: 
      - ./server/:/server
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  #client:  
   # build: ./client
   # volumes: 
   #   - ./client/:/usr/src/app
   # ports: 
   #   - "4200:4200"     
   # command: npm start